name: expense_offline_repository
description: offline-expense-repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.9.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
